version: "3.4"

services:
    pgAdmin:
        image: dpage/pgadmin4
        container_name: $PGADMIN_DEFAULT_HOST
        expose:
          - 80
        ports:
            - $PGADMIN_DEFAULT_PORT:80
        environment:
            PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
            PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
        volumes:
            - pgadmin:/var/lib/pgadmin

    postgres:
        image: postgres
        container_name: $POSTGRES_HOST
        expose:
          - 5432
        ports:
            - $POSTGRES_PORT:5432
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
        depends_on:
            - pgAdmin
        volumes:
            - pgvol:/var/lib/postgresql/data


volumes:
    pgvol:
    pgadmin: 